2021-10-28 14:37:14.225881: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /software/slurm-current-el7-x86_64/lib64:/software/slurm-current-el7-x86_64/lib:/software/cuda-10.1-el7-x86_64/extras/CUPTI/lib64:/software/cuda-10.1-el7-x86_64/lib64:/software/python-anaconda-2020.02-el7-x86_64/lib:/software/git-2.10-el7-x86_64/lib64:/software/subversion-1.9.4-el7-x86_64/lib:/software/serf-1.3.9-el7-x86_64/lib
2021-10-28 14:37:14.229522: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-28 14:37:14.229614: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (dali006.rcc.local): /proc/driver/nvidia/version does not exist
2021-10-28 14:37:14.230420: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2021-10-28 14:37:14.255260: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
2021-10-28 14:37:14.258344: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55beab741e10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-10-28 14:37:14.258400: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-10-28 14:37:24.672007: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2021-10-28 14:37:25.160714: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.1
2021-10-28 14:37:25.276636: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_NOT_INITIALIZED
2021-10-28 14:37:25.277739: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1355] function cupti_interface_->ActivityEnable(activity)failed with error CUPTI_ERROR_NOT_INITIALIZED
2021-10-28 14:37:31.228715: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2021-10-28 14:37:31.228904: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2021-10-29 01:45:30.438445: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2021-10-29 01:45:30.446409: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_NOT_INITIALIZED
2021-10-29 01:45:30.446996: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1355] function cupti_interface_->ActivityEnable(activity)failed with error CUPTI_ERROR_NOT_INITIALIZED
2021-10-29 01:45:36.443822: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2021-10-29 01:45:36.443984: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2021-10-29 09:05:32.308979: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2021-10-29 09:05:32.373101: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI_ERROR_NOT_INITIALIZED
2021-10-29 09:05:32.373715: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1355] function cupti_interface_->ActivityEnable(activity)failed with error CUPTI_ERROR_NOT_INITIALIZED
2021-10-29 09:05:38.236833: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI_ERROR_INVALID_PARAMETER
2021-10-29 09:05:38.236990: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
